sudo: required
services:
  - docker

before_install:
  - echo "Lets do this"

script:
  - docker build -t phiratio/docker-react -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "agp"
  env: "Agp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-000243498884"
  bucket_path: "agp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

