sudo: required
services:
  - docker

before_install:
  - docker build -t phiratio/docker-react -f Dockerfile.dev .

script:
  - docker run phiratio/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "agp"
  env: "Agp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-000243498884"
  bucket_path: "agp"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

